/**
 * Better-Auth server-side configuration.
 * Handles database integration via Prisma, configures authentication providers,
 * and manages the lifecycle of email verification and password resets.
 */
import { betterAuth } from "better-auth"; // Core library function to initialize the Better-Auth service
import { prismaAdapter } from "better-auth/adapters/prisma"; // Prisma database adapter tailored for Better-Auth
import prisma from "./prisma"; // The project's singleton Prisma database client instance
import { Resend } from "resend"; // Resend SDK for sending transactional emails
import { AuthEmailTemplate } from "@/components/emails/auth-email-template"; // React component acting as template for auth emails

/**
 * Initialize the Resend mail client using the secret API key from environment variables.
 * This client is used to dispatch transactional emails (e.g., verification, reset).
 */
const resend = new Resend(process.env.RESEND_API_KEY);

/**
 * Create and export the configured authentication service instance.
 * This is used in API routes and server-side logic to handle auth requests.
 */
export const auth = betterAuth({
  /**
   * Use Prisma as the database adapter to persist user accounts, sessions, and social connections.
   * This allows Better-Auth to manage user data directly within our existing PostgreSQL schema.
   */
  database: prismaAdapter(prisma, {
    provider: "postgresql", // Matches the Prisma provider type defined in schema.prisma.
  }),

  /**
   * Configure Email and Password authentication strategy.
   * Includes verification flow and password recovery logic.
   */
  emailAndPassword: {
    enabled: true, // Allow users to sign up and log in using an email and password.
    requireEmailVerification: true, // Prevent users from logging in until they have verified their email.

    /**
     * Custom asynchronous callback triggered when a user requests a password reset.
     * @param user - The user object requesting the reset.
     * @param url - The reset password URL generated by Better-Auth.
     */
    sendResetPassword: async ({ user, url }) => {
      try {
        // Attempt to dispatch the password reset email via Resend's API.
        const { error } = await resend.emails.send({
          from: "Axis <noreply@lwshakib.site>", // The verified sender identity
          to: user.email, // Recipient's email address
          subject: "Reset your password", // Email subject line
          react: AuthEmailTemplate({ type: "forgot-password", url }), // Render React Email template
        });

        // Log and handle explicit errors returned by the Resend API
        if (error) {
          console.error("Failed to send email via Resend:", error);
          throw new Error("Failed to send authentication email.");
        }
      } catch (err) {
        // Catch network errors or unexpected exceptions
        console.error("Resend error:", err);
        throw err;
      }
    },
  },

  /**
   * Configure OAuth providers for fast, passwordless onboarding.
   */
  socialProviders: {
    google: {
      enabled: true, // Activate "Sign in with Google" strategy.
      // Load Google API credentials from secure environment variables.
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    },
  },

  /**
   * Settings pertaining to the email verification lifecycle.
   */
  emailVerification: {
    sendOnSignUp: true, // Automatically trigger the verification email immediately after signup.

    /**
     * Custom asynchronous callback triggered to deliver the verification link.
     * @param user - The newly registered user object.
     * @param url - The verification URL generated by Better-Auth.
     */
    sendVerificationEmail: async ({ user, url }) => {
      try {
        // Dispatch the account verification email via Resend's API.
        await resend.emails.send({
          from: "Axis <noreply@lwshakib.site>",
          to: user.email,
          subject: "Verify your email address",
          react: AuthEmailTemplate({ type: "email-verification", url }), // Render verification template
        });
      } catch (err) {
        // Log errors to the server console if the verification email fails to send
        console.error("Verification email error:", err);
      }
    },
  },

  /**
   * Adjust application-wide account level settings.
   */
  account: {
    accountLinking: {
      enabled: true, // Links multiple providers (e.g. Google and Email) to one account if emails match.
    },
  },
});
